### ISSUE TITLE
When does 19.04 come for Raspberry Pi? 

### ISSUE THREAD

**Issue by komape** [ubuntu-mate/ubuntu-mate-pi#2]
Does anybody have information about the release date for 19.04 for the Raspberry Pi?

**Comment by lah7** [comment]
Please see the project leader's post here:

[https://ubuntu-mate.community/t/support-for-raspberry-pi-4/19757/7](https://ubuntu-mate.community/t/support-for-raspberry-pi-4/19757/7?u=lah7)

> I won't be giving at ETA because I'll be working on this project in my spare time which will be in short supply in the coming months. I have 2 Pi 4 devices and am just as keen to get them running Ubuntu MATE as anyone else :slightly_smiling_face:

I can't confirm if it will be the 19.04 release specifically or if it will be based on 18.04 LTS.

**Comment by komape** [comment]
Thanks. 

Do you also know how about 19.04 for the Raspberry Pi 3 B+?

**Comment by flexiondotorg** [comment]
Undecided as to which Ubuntu version we'll target, my preference would be 18.04 but I'll know more when I get into the work. I'll close this issue since the release of the Pi images is unrelated to the project.
